In [1]:
import numpy as np

In [7]:
#Create a 1D array of numbers from 0 to 9

task1 = np.arange(10)
print(task1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
#Create a 3x3 NumPy array of all Boolean value Trues

task2 = np.ones(9).reshape(3,3)
print(task2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
#Extract all odd numbers from an array of 1-10

task3 = np.arange(1,11)
task3 = np.delete(task3, task3%2==1)

print(task3)

[ 2  4  6  8 10]


In [31]:
#Replace all odd numbers in an array of 1-10 with the value -1

task4 = np.arange(1,11)
task4[task4%2==1]=-1

print(task4)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [33]:
#Convert a 1D array to a 2D array with 2 rows

task5 = np.arange(3,29,5)
task5 = task5.reshape(2,3)

print(task5)

[[ 3  8 13]
 [18 23 28]]


In [45]:
#Create two arrays a and b, and stack these two arrays vertically using np.dot and np.sum to calculate totals

a = np.random.rand(4,4)
b = np.random.rand(4,4)

c = np.vstack((a,b))

print(c)

[[0.54494908 0.1528191  0.43185007 0.21388815]
 [0.51414562 0.00813742 0.17890475 0.88325985]
 [0.55836704 0.02382407 0.85276445 0.9699807 ]
 [0.51235405 0.45556134 0.69855343 0.81412924]
 [0.32898338 0.40929778 0.6849249  0.19149737]
 [0.12701283 0.88580971 0.80816581 0.13893123]
 [0.56290117 0.08375102 0.83216398 0.35054237]
 [0.29629054 0.46909521 0.36989496 0.552662  ]]


In [46]:
d = np.dot(a,b)

print(d)

[[0.50515112 0.49491688 0.93523859 0.39517727]
 [0.53258615 0.64696329 0.83431898 0.65044593]
 [0.95413765 0.77607518 1.47012412 0.94523728]
 [0.86085344 1.05365473 1.60154646 0.85621703]]


In [48]:
s = np.sum(d)

print(s)

13.512644089043718
